### ISSUE TITLE
any idea on this?

### ISSUE THREAD

**Issue by dutch3000** [santoshjpawar/concourse-email-notification#5]
v1.0.10-17dce345143614aa96d9a57c3f6ab8c5d6f3e664 - missing required field "source.smtp.host"
failed

in my pipeline:

  - name: email-notification-r
    type: email-notification-resource
    source:
      anonymous: true
      smtp_host: smtp.company.com
      smtp_port: "25"
      default_recipient: "userid@email.com"

**Comment by kwladyka** [comment]
You don't have "tab" in lines after `source:`. I think issue can be closed.

**Comment by dutch3000** [comment]
thanks!
